global CLIENTS_CONNECTED
global HOST
global PORT
global FRAMELENGTH

CLIENTS_CONNECTED = []
HOST = "127.0.0.1"
PORT = 1212
FRAME_LENGTH = 1415
MAX_CLIENTS = 50
MAX_ID = 32767
DURATION_TIMER = 2
TRY_MAX = 15
POWER_ON = True
ERROR_RATE = 0

COMMANDS = []

# Log variables
DEBUG = False
INFO = False