global CLIENTS_CONNECTED
global HOST
global PORT
global FRAMELENGTH

CLIENTS_CONNECTED = []
HOST = "localhost"
PORT = 1212
FRAME_LENGTH = 1415
MAX_CLIENTS = 10
MAX_ID = 32767
DURATION_TIMER = 2
TRY_MAX = 7
POWER_ON = True
ERROR_RATE = 30

COMMANDS = []